### ISSUE TITLE
isSubscribedBy expects an int

### ISSUE THREAD

**Issue by ctf0** [LiliomLab/laravel-acquaintances#12]
https://github.com/LiliomLab/laravel-acquaintances/blob/bf357d93537c0dbc4f80531938d605e9473baee8/src/Traits/CanBeSubscribed.php#L13-L23

does it mean i should send an id or is it a doc typo ?

**Comment by mkwsra** [comment]
It's a typo, it should not be int
It should be an eloquent object

**Comment by ctf0** [comment]
i will send a PR with the fix
