### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by ctf0** [LiliomLab/laravel-acquaintances#14]
first many thanx for the package, it did help alot, however there is a room for improvements ex.

- the friendship group could be saved into db with a seeder & use it like any other relation without the need for accessing the config & making a lockup using the id
- atm the models are not extendable, so to get around that we can add the models namespaces to the config.
- update the events in the readme with their payload/params.
- update the readme with a section on how to use UUID instead of IDs for the relations
- add a couple of helper methods like `toggleFriendship`
- [this section](https://github.com/LiliomLab/laravel-acquaintances#to-filter-friendships-by-group-you-can-pass-a-group-slug) might be wrong, because you cant group a friend unless it was accepted first

i'll be more than happy to submit a PR for any.

**Comment by mkwsra** [comment]
Thank you so much for this great feedback! I really appreciate it, and thanks for using the package.

Please feel free to add whatever you want whenever you can, and I will do my best to take these in consideration 👍

**Comment by ctf0** [comment]
if you have some notes on any b4 i work it, plz do tell :1st_place_medal:

**Comment by mkwsra** [comment]
Nothing really, everything is great and you are much-appreciated dear fellow
