### ISSUE TITLE
DB migration fails on users.id foreign key

### ISSUE THREAD

**Issue by GreenImp** [LiliomLab/laravel-acquaintances#4]
In Laravel 5.8, When running the migration files that come with the package it throws an error when running the `2018_06_14_000000_create_acquaintances_interactions_table` migration:

```
Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `interactions` add constraint `interactions_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update cascade)
```

This is because the `users.id` field is no longer a `unsignedInteger`, it has been changed to an `unsignedBigInteger`.

Changing the migration file line 19, from this:
```php
$table->unsignedInteger('user_id')->index();
```
To this:
```php
$table->unsignedBigInteger('user_id')->index();
```

Fixes the problem.

I'm not sure if you'd want to add this change to your package, as I think it would then break on older versions of Laravel, that still use the `unsignedInteger` ID field type.

**Comment by mkwsra** [comment]
Thanks a lot for your feedback and the explanation, I shall add this change and issue a new version/tag for this library.

You are much appreciated!

**Comment by GreenImp** [comment]
I've created a pull request for this (#7) as I was already in the code to look at #5.
