### ISSUE TITLE
`Illuminate\Events\Dispatcher::fire()` removed in 5.8

### ISSUE THREAD

**Issue by GreenImp** [LiliomLab/laravel-acquaintances#5]
In Laravel 5.8, the `Illuminate\Events\Dispatcher::fire()` method has been deprecated removed from the codebase, meaning that whenever this package triggers and event it throws a fatal error:

> Call to undefined method Illuminate\Events\Dispatcher::fire()

This can be fixed by replacing`::fire()` with `::dispatch()`. I'm happy to put a pull request together if you're okay with that?

**Comment by mkwsra** [comment]
Yes, for sure it's okay and if you aren't free I will do so very soon

**Comment by GreenImp** [comment]
Fab, I've created a pull request which should fix the problem. I've not been able to test it properly though. You can see my comment on the pull request.

**Comment by mkwsra** [comment]
Thank you!
