### ISSUE TITLE
Difference between "Like" and "Favourite"?

### ISSUE THREAD

**Issue by GreenImp** [LiliomLab/laravel-acquaintances#9]
Hi,
What is the difference between "Liking" a model and "Favouriting" a model? Do they work in exactly the same way, just with a different name?

**Comment by mkwsra** [comment]
Hi,

Yes they are the same.
Such thing is implemented in case you would like you app to implement both
of them at the same time.

**Comment by GreenImp** [comment]
That's fab, thank you.
